### ISSUE TITLE
guy-image

### ISSUE THREAD

**Issue by MarcJPH** [Code-Institute-Org/gitpod-full-template#14]
![guy-image](https://user-images.githubusercontent.com/75221904/105089853-90267b00-5a95-11eb-8469-49123c21342c.png)

**Comment by TravelTimN** [comment]
@MarcJPH 
Did you mean to open a new "Issue" regarding this image?
Note: it will not be added to the template, and I will close this Issue.
If this is a valid Issue you'd like to report on the Gitpod template, please reply here, and we'll discuss further.
