### ISSUE TITLE
girl-image

### ISSUE THREAD

**Issue by MarcJPH** [Code-Institute-Org/gitpod-full-template#15]
![girl-image](https://user-images.githubusercontent.com/75221904/105089916-a3394b00-5a95-11eb-9fc8-ae6515ff7aa1.png)

**Comment by TravelTimN** [comment]
@MarcJPH 
Did you mean to open a new "Issue" regarding this image?
Note: it will not be added to the template, and I will close this Issue.
If this is a valid Issue you'd like to report on the Gitpod template, please reply here, and we'll discuss further.
